server:
  port: 8080
  name: jpa demo
  version: public

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_jpa?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=UTC&useSSL=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true